### ISSUE TITLE
java.lang.NoClassDefFoundError: clojure.lang.Var

### ISSUE THREAD

**Issue by Oscargp1986** [yogthos/json-to-pdf#12]
I was getting the same error than others trying to add the repository and library on gradle, so I tried to download the jar (json-to-pdf-0.7.5.jar), copy it to libs folder and add compile files('libs/json-to-pdf-0.7.5.jar') to gradle.

The project compiles fine but when I try to run JsonPDF.writeToFile I get this error:

`FATAL EXCEPTION: main
                                                                         Process: com.trecone.jsonpdftest, PID: 14043
                                                                         java.lang.NoClassDefFoundError: clojure.lang.Var
                                                                             at org.yogthos.JsonPDF.<clinit>(Unknown Source)
                                                                             at com.trecone.jsonpdftest.MainActivity.onCreate(MainActivity.java:121)
                                                                             at android.app.Activity.performCreate(Activity.java:5458)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:174)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:146)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                             at dalvik.system.NativeStart.main(Native Method)`

**Comment by yogthos** [comment]
looks like the same issue as this one https://github.com/yogthos/json-to-pdf/issues/11 unfortunately, I'm not sure what gradle's doing that cause sit
